mvcProj/Models/ErrorViewModel.cs
namespace mvcProj.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

mvcProj/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace mvcProj.Models
{
public class Student {
    [Key]
    public int StudentId { get; set; }
    [Required]
    public string StudentName { get; set;  }
    [Required]
    public int Age { get; set;  }
}
}

mvcProj/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace mvcProj.Models {
    public class Teacher
    {
        [Required]
        public int TeacherId { get; set;}
        [Required]
        public string TeacherName { get; set; }
        [Required]
        public string TeacherSub { get; set; }
    }

}

mvcProj/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvcProj.Models;

namespace mvcProj.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

mvcProj/Controllers/StudentController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using mvcProj.Models;

namespace mvcProj.Controllers;

public class StudentController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public StudentController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

mvcProj/Controllers/TeacherController.cs
using mvcProj;
using mvcProj.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mvcProj.Controllers
{
    public class TeacherController : Controller {
        private readonly ApplicationDbContext _db;

        public TeacherController(ApplicationDbContext db)
        {
            _db = db;
        }
        // public IActionResult Index()
        // {
        //     IEnumerable<Teacher> listofteachers = _db.Teacher;
        //     return View(listofteachers);
        // }

        // querying searchString
        [HttpPost]
        public async Task<IActionResult> Index(string searchString)
        {
            var teachers = from t in _db.Teacher
                           select t;
            if(!String.IsNullOrEmpty(searchString))
            {
                teachers = teachers.Where(s => s.TeacherName!.Contains(searchString));
            }

            return View(await teachers.ToListAsync());

        }

        // direct searching without querying
        // public async Task<IActionResult> Index(string id)
        // {
        //     var teachers = from t in _db.Teacher
        //                    select t;
        //     if(!String.IsNullOrEmpty(id))
        //     {
        //         teachers = teachers.Where(s => s.TeacherName!.Contains(id));
        //     }

        //     return View(await teachers.ToListAsync());
        // }

        public IActionResult Create()
        {
            // PopulateSubjectsDropDownList(); 
            return View();
        }

        [HttpPost]
        public IActionResult Create([Bind("TeacherName,TeacherSub")] Teacher teacherobj)
        {
            if (ModelState.IsValid)
            {
                _db.Teacher.Add(teacherobj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(teacherobj);
        }

        [HttpGet]
        public IActionResult Edit(int teacherid)
        {
            var teacherobj = _db.Teacher.Find(teacherid);
            return View(teacherobj);
        }

        [HttpPost] 
        public IActionResult Edit(Teacher updatedvaluesobj)
        {
            _db.Teacher.Update(updatedvaluesobj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int TeacherId)
        {
            var teacherobj = _db.Teacher.Find(TeacherId);
            return View(teacherobj);
        }

        [HttpPost]
        public IActionResult DeletePost(int teacherId)
        {
            var teacherobj = _db.Teacher.Find(teacherId);

            if(ModelState.IsValid)
            {
                _db.Teacher.Remove(teacherobj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(teacherobj);
        }

        
    }
}

mvcProj/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvcProj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvcProj</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvcProj.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvcProj</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - mvcProj - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mvcProj/Views/Student/Index.cshtml
@{
    ViewData["Title"] = "Student Page";
}

<div class="text-center">
    <h1 class="display-4">Student page in student controller</h1>
</div>

mvcProj/Views/Teacher/Create.cshtml
@model mvcProj.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<form method="post" asp-action="Create">
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Teacher</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="TeacherName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherName" class="form-control" />
                        <span asp-validation-for="TeacherName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="TeacherSub"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherSub" class="form-control" />
                        <span asp-validation-for="TeacherSub" class="text-danger"></span>
                    </div>
                </div>
                @* <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Subject" class="control-label"></label>
                    </div>
                    <div class="col-8">
                        <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId">
                            <option value="">--Select Subject--</option>
                        </select>
                        
                        <span asp-validation-for="SubjectId" class="text-danger"></span>
                    </div>

                </div> *@
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

mvcProj/Views/Teacher/Delete.cshtml
@model mvcProj.Models.Teacher

<form method="post" asp-action="DeletePost">
    <input asp-for="TeacherId" hidden />
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Teacher Details</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="TeacherName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherName" disabled class="form-control" />
                        <span asp-validation-for="TeacherName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="TeacherSub"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherSub" disabled class="form-control" />
                        <span asp-validation-for="TeacherSub" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

mvcProj/Views/Teacher/Edit.cshtml
@model mvcProj.Models.Teacher

<form method="post" asp-action="Edit">
    <input hidden asp-for="TeacherId" />
    <div class="border p-3 bg-white">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Teacher details</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="TeacherName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherName" class="form-control" />
                        <span asp-validation-for="TeacherName" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="TeacherSub"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TeacherSub" class="form-control" />
                        <span asp-validation-for="TeacherSub" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update Teacher Details" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

mvcProj/Views/Teacher/Index.cshtml
@model IEnumerable<mvcProj.Models.Teacher>

@{
    ViewData["Title"] = "Teacher Page";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-8">
            <h2 class="text-primary">Teacher List</h2>
        </div>
        <a asp-controller="Teacher" asp-action="Create" class="btn btn-primary">
        Add New Teacher
        </a>
    </div>
    <br />

    <form asp-controller="Teacher" asp-action="Index">
        <p>
            Name : <input type="text" name="SearchString" />
            <input type="submit" value="Filter">
        </p>
    </form>

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Teacher Name</th>
                    <th>Subject</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj1 in Model)
                {
                    <tr>
                        <td width="50%">@obj1.TeacherName</td>
                        <td>@obj1.TeacherSub</td>
                        <td>
                           <a asp-controller="Teacher" asp-action="Edit" asp-route-teacherid="@obj1.TeacherId" class="btn btn-primary">Edit</a>
                            <a asp-controller="Teacher" asp-action="Delete" asp-route-teacherid="@obj1.TeacherId" class="btn btn-primary">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No teacher details.</p>
    }
</div>